#!/bin/bash
# Add or remove the macOS-derived speaker EQ output "MacBook Speakers (EQ)". Run as your user, NO sudo.
#   bash audio/scripts/speaker-eq.sh install
#   bash audio/scripts/speaker-eq.sh remove
#
# The EQ (preamp, high-pass, 7-band parametric per side, derived from macOS AppleHDA layout100) was published
# by thomas-shirley/macbook8.1-speaker-driver without a license, so it is not redistributed here. This script
# downloads that file at a pinned commit, verifies its checksum, and adapts it for this setup:
#   - sink name mb81_speakers_eq / "MacBook Speakers (EQ)", playback into the raw node mb81_speakers
#   - node.target -> target.object (PipeWire 1.x), capture node named explicitly
#   - never add node.dont-reconnect: at PipeWire start the raw node does not exist yet, the stream would
#     fail and the filter-chain module would unload itself silently.
set -euo pipefail

UPSTREAM_COMMIT=fe54ad1aa7d8448fc49c0b5c8b353c50e2b1b8a1
UPSTREAM_URL="https://raw.githubusercontent.com/thomas-shirley/macbook8.1-speaker-driver/$UPSTREAM_COMMIT/51-macbook81-speaker.conf"
UPSTREAM_SHA256=9fb5b9c610a0cf704f34f8873bca28a200830a7408151f7da244d80e203a8d8d
DIR=$HOME/.config/pipewire/pipewire.conf.d
CONF=$DIR/52-mb81-speaker-eq.conf
[ "$(id -u)" != 0 ] || { echo "Run WITHOUT sudo."; exit 1; }

node_id() {
  pw-dump | python3 -c 'import json,sys; print(next((o["id"] for o in json.load(sys.stdin) if o.get("type","").endswith(":Node") and ((o.get("info") or {}).get("props") or {}).get("node.name")==sys.argv[1]), ""))' "$1"
}

case "${1:-}" in
  install)
    [ -n "$(node_id mb81_speakers)" ] || { echo "ABORT: run 'bash audio/scripts/pipewire-speakers.sh install' first."; exit 1; }
    tmp=$(mktemp)
    trap 'rm -f "$tmp"' EXIT
    curl -fsSL "$UPSTREAM_URL" -o "$tmp"
    echo "$UPSTREAM_SHA256  $tmp" | sha256sum -c --quiet || { echo "ABORT: upstream file changed (checksum mismatch)"; exit 1; }
    mkdir -p "$DIR"
    python3 - "$tmp" "$CONF" "$UPSTREAM_COMMIT" <<'PY'
import sys
src, dst, commit = sys.argv[1], sys.argv[2], sys.argv[3]
s = open(src).read()
s = s[s.index("context.modules"):]
def sub(old, new):
    global s
    if s.count(old) != 1:
        sys.exit("ABORT: unexpected upstream content near: " + old)
    s = s.replace(old, new)
sub('node.name        = "MacBook_Speaker"', 'node.name        = "mb81_speakers_eq"')
sub('node.description = "MacBook Speaker (EQ)"', 'node.description = "MacBook Speakers (EQ)"')
sub('priority.session = 1100', 'priority.session = 2100')
sub('''            capture.props = {
                media.class    = "Audio/Sink"''', '''            capture.props = {
                node.name      = "mb81_speakers_eq"
                node.description = "MacBook Speakers (EQ)"
                media.class    = "Audio/Sink"
                priority.session = 2100''')
sub('node.name         = "MacBook_Speaker_DSP_Out"', 'node.name         = "mb81_speakers_eq_out"')
sub('node.target       = "MacBook_Speaker_Raw"', 'target.object     = "mb81_speakers"')
header = ("# MacBook8,1 speaker EQ, generated by audio/scripts/speaker-eq.sh.\n"
          "# EQ values: thomas-shirley/macbook8.1-speaker-driver 51-macbook81-speaker.conf @ %s\n"
          "# (derived from macOS AppleHDA layout100). Adapted node names and target for this setup.\n" % commit)
open(dst, "w").write(header + s)
PY
    echo "installed $CONF"
    ;;
  remove)
    rm -f "$CONF" && echo "removed $CONF"
    ;;
  *) echo "usage: $0 install|remove"; exit 1 ;;
esac

systemctl --user restart pipewire pipewire-pulse wireplumber
sleep 5
if [ "$1" = install ]; then
  id=$(node_id mb81_speakers_eq)
  if [ -n "$id" ]; then
    jack=$(amixer -c PCH cget iface=CARD,name='Headphone Jack' 2>/dev/null | sed -n 's/.*: values=//p')
    [ "$jack" = off ] && wpctl set-default "$id"
    echo "OK: 'MacBook Speakers (EQ)' is available (id $id)."
  else
    echo "PROBLEM: the EQ output did not appear. Undo: bash $0 remove"
    exit 1
  fi
fi
wpctl status | sed -n '/^Audio/,/^Video/p' | sed -n '/Sinks:/,/Sources:/p'
